[package]
name = "websoket"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-channel = "0.3.27"
futures-util = "0.3.27"
tokio = { version = "1.26.0", features = ["full"] }
tokio-tungstenite = "0.18.0"
tungstenite = "0.18.0"
